TrabajoPracticoWeb3/Controllers/PeliculasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrabajoPracticoWeb3.App_Data;
using TrabajoPracticoWeb3.Models;

namespace TrabajoPracticoWeb3.Controllers
{
    public class PeliculasController : Controller
    {
        // GET: Peliculas
        public ActionResult Reserva(int idPelicula = -1)
        {
            ViewData["error"] = null;

            if (TempData["IdPelicula"] != null) {

                ViewData["error"] = "Por favor, no deje ningun campo vacio";

                string temp = (string)TempData["IdPelicula"];

                int IdPelicula2;

                Int32.TryParse(temp, out IdPelicula2);

                idPelicula = IdPelicula2;
            }

            
            myContext ctx = new myContext();

            var Pelicula = PeliculaServicio.TraerPelicula(idPelicula);

            SelectList Versiones = PeliculaServicio.MostrarVersionCascada(idPelicula);

            ViewData["version"] = Versiones;
            return View(Pelicula);
        }
        //Select en cascada
        public JsonResult GetSede(string idVersion, string idPelicula)
        {
            SelectList Sede = PeliculaServicio.MostrarSedeCascada(idPelicula, idVersion);

            return Json(Sede);
        }

        public JsonResult GetDia(string idSede, string idPelicula, string idVersion)
        {
            SelectList Dia = PeliculaServicio.MostrarDiaCascada(idPelicula, idVersion, idSede);

            return Json(Dia);
        }

        public JsonResult GetHorario(string idDia, string idSede, string idVersion, string idPelicula)
        {
            SelectList Horarios = PeliculaServicio.MostrarHorarioCascada(idPelicula, idVersion, idSede);

            return Json(Horarios);
        }

        public ActionResult FinalizarReserva()
        {
            if (Request["Sede"] == "0" || Request["Version"] == "0" || Request["Horario"] == "0" || Request["Dia"] == "0" || Request["Sede"] == "" || Request["Version"] == "" || Request["Horario"] == "" || Request["Dia"] == "")
            {

                TempData["IdPelicula"] = Request["Pelicula"];
                return RedirectToAction("Reserva");
            }
            else { 
            myContext ctx = new myContext();

            int IdPelicula, IdSede, IdVersion;

            Int32.TryParse(Request["Pelicula"], out IdPelicula);
            Int32.TryParse(Request["Sede"], out IdSede);
            Int32.TryParse(Request["Version"], out IdVersion);

            var a = ctx.Carteleras.Where(x => x.IdPelicula == IdPelicula && x.IdSede == IdSede && x.IdVersion == IdVersion).First();
            ViewBag.ImagenPelicula = ctx.Peliculas.Where(x => x.IdPelicula == IdPelicula).FirstOrDefault().Imagen;
            ViewBag.TiposDocumentos = PeliculaServicio.TraeTiposDeDocumentos();

            CarteleraReserva cr = new CarteleraReserva();
            cr.IdPelicula = a.IdPelicula;
            cr.IdSede = a.IdSede;
            cr.NumeroSala = a.NumeroSala;
            cr.IdVersion = a.IdVersion;
            cr.Peliculas = a.Peliculas;
            cr.Sedes = a.Sedes;
            cr.Versiones = a.Versiones;
            cr.Horario = Request["Horario"];
            cr.Dia = Request["Dia"];

            return View(cr);

            }
        }
        [HttpPost]
        public ActionResult ConfirmarReserva(CarteleraReserva cr)
        {
            myContext ctx = new myContext();

            if (ModelState.IsValid)
            {
                Reservas reserva = new Reservas();

                string HoraInicio = cr.Horario.ToString();
                int sitioDeCorte = 2;
                string parte1 = HoraInicio.Substring(0, sitioDeCorte);
                string parte2 = HoraInicio.Substring(3, sitioDeCorte);

                int HoraInicioParte1, HoraInicioParte2;

                Int32.TryParse(parte1, out HoraInicioParte1);
                Int32.TryParse(parte2, out HoraInicioParte2);
                DateTime Hora = DateTime.Today;

                Hora = Hora.AddHours(HoraInicioParte1);
                Hora = Hora.AddMinutes(HoraInicioParte2);

                reserva.IdPelicula = cr.IdPelicula;
                reserva.IdVersion = cr.IdVersion;
                reserva.IdSede = cr.IdSede;
                reserva.FechaHoraInicio = Hora;
                reserva.FechaCarga = DateTime.Now;
                reserva.Email = cr.Email;
                reserva.IdTipoDocumento = cr.IdTipoDocumento;
                reserva.NumeroDocumento = cr.NumeroDocumento;
                reserva.CantidadEntradas = cr.CantidadEntradas;

                ctx.Reservas.Add(reserva);
                ctx.SaveChanges();


                cr.IdReserva = reserva.IdReserva;
                var sede = ctx.Sedes.Where(x => x.IdSede == cr.IdSede).FirstOrDefault();
                ViewBag.PrecioTotal = cr.CantidadEntradas * sede.PrecioGeneral;

                return View(cr);
            }

            var a = ctx.Carteleras.Where(x => x.IdPelicula == cr.IdPelicula && x.IdSede == cr.IdSede && x.IdVersion == cr.IdVersion).First();
            ViewBag.ImagenPelicula = ctx.Peliculas.Where(x => x.IdPelicula == cr.IdPelicula).FirstOrDefault().Imagen;
            ViewBag.TiposDocumentos = PeliculaServicio.TraeTiposDeDocumentos();

            cr.IdPelicula = a.IdPelicula;
            cr.IdSede = a.IdSede;
            cr.NumeroSala = a.NumeroSala;
            cr.IdVersion = a.IdVersion;
            cr.Peliculas = a.Peliculas;
            cr.Sedes = a.Sedes;
            cr.Versiones = a.Versiones;
            cr.Horario = cr.Horario;
            cr.Dia = cr.Dia;
            return View("FinalizarReserva", cr);

        }


    }
}

TrabajoPracticoWeb3/Views/Peliculas/ConfirmarReserva.cshtml
@{
    ViewBag.Title = "ConfirmarReserva";
    Layout = "~/Views/Shared/_LHome.cshtml";
}
@model  TrabajoPracticoWeb3.Models.CarteleraReserva


<h2 class="">Detalle de reserva realizada</h2>

 <div class="col-md-6 col-md-offset-3 table-bordered">
    <h3 class="text-center">Código de reserva: @Model.IdReserva</h3>
    <h3 class="text-center">Cantidad de entradas: @Model.CantidadEntradas</h3>
    <h3 class="text-center">Precio total: @ViewBag.PrecioTotal</h3>
    <h3 class="label label-success text-center">Su reserva se ha realizado con éxito!!! Muchas gracias!</h3>
</div>
<div class="col-md-12 col-md-1">
    <button class="btn btn-info btn-lg">Volver a Cartelera</button>
</div>

TrabajoPracticoWeb3/Views/Peliculas/FinalizarReserva.cshtml
@{
    ViewBag.Title = "FinalizarReserva";
    Layout = "~/Views/Shared/_LHome.cshtml";   
}
@model  TrabajoPracticoWeb3.Models.CarteleraReserva

<h2>Finalizar Reserva</h2>

@using (Html.BeginForm("ConfirmarReserva", "Peliculas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.Hidden("IdPelicula", Model.IdPelicula)
    @Html.Hidden("IdVersion", Model.IdVersion)
    @Html.Hidden("IdSede", Model.IdSede)
    @Html.Hidden("Dia", Model.Dia)
    @Html.Hidden("Horario", Model.Horario)

    <div class="movie">
        <h2 class="page-heading">@Model.Peliculas.Nombre</h2>
        <div class="movie__info">
            <div class="col-sm-4 col-md-4 movie-mobile">
                <div class="movie__images">
                    <img class="img-responsive" src='@Url.Action("GetImage", "Home", new { image =  @ViewBag.ImagenPelicula.ToString() } )'>
                </div>
            </div>
            <div class="col-sm-4 col-md-4">
                <p class="movie__time">@Model.Peliculas.Duracion Min</p>
                <p class="movie__option"><strong>Descripcion: </strong>@Model.Peliculas.Descripcion</p>
                <p class="movie__option"><strong>Sede: </strong>@Model.Sedes.Nombre</p>
                <p class="movie__option"><strong>Version: </strong>@Model.Versiones.Nombre</p>
                <p class="movie__option"><strong>Dia: </strong>@Model.Dia</p>
                <p class="movie__option"><strong>Horario: </strong>@Model.Horario</p>
                <p class="movie__option"><strong>Sala: </strong>@Model.NumeroSala</p>
                <p class="movie__option"><strong>Genero: </strong>@Model.Peliculas.Generos.Nombre</p>
                <p class="movie__option"><strong>Clasificacion: </strong>@Model.Peliculas.Calificaciones.Nombre</p>
                <p class="movie__option"><strong>Precio: </strong>@Model.Sedes.PrecioGeneral</p>
            </div>
            <div class="col-sm-4 col-md-4">
                <div class="form-group">
                    @Html.LabelFor(x => x.Email)
                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control", @maxlength = "40" })
                    <span class="text-danger">@Html.ValidationMessageFor(x => x.Email)</span>
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.IdTipoDocumento)
                    @Html.DropDownListFor(x => x.IdTipoDocumento, new SelectList(ViewBag.TiposDocumentos, "IdTipoDocumento", "Descripcion"), new { @class = "form-control" })
                    <span class="text-danger"> @Html.ValidationMessageFor(x => x.IdTipoDocumento)</span>
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.NumeroDocumento)
                    @Html.TextBoxFor(x => x.NumeroDocumento, new { @class = "form-control", @maxlength = "8" })
                    <span class="text-danger">@Html.ValidationMessageFor(x => x.NumeroDocumento)</span>
                </div>

                <div class="form-group">
                    @Html.LabelFor(x => x.CantidadEntradas)
                    @Html.TextBoxFor(x => x.CantidadEntradas, new { @class = "form-control", @maxlength = "4", Value = "" })
                    <span class="text-danger">@Html.ValidationMessageFor(x => x.CantidadEntradas)</span>
                </div>
                <button type="submit" class="btn btn-success">Confirmar Reserva</button>
            </div>
        </div>
    </div>

    <br />
    <div>
        <span class="text-center label label-info">La reserva estará vigente hasta 1hr antes de la función elegida y deberá ser confirmada en el cine seleccionado.</span>
    </div>
}

TrabajoPracticoWeb3/Views/Peliculas/Reserva.cshtml
@{
    ViewBag.Title = "Reserva";
    Layout = "~/Views/Shared/_LHome.cshtml";


}

@model IEnumerable<TrabajoPracticoWeb3.App_Data.Peliculas>

@foreach(var pelicula in Model) { 
<h2>@pelicula.Nombre</h2>

<div class="row row-con-margin">
    <div class="col-md-4">
        <div>
            <img class="img-responsive" src='@Url.Action("GetImage", "Home", new { image = pelicula.Imagen.ToString() } )'>
        </div>
    </div>
    <div class="col-md-4">
        <h4>Sinopsis</h4>
        <p>@pelicula.Descripcion</p>

    </div>
    <div class="col-md-4">

        @using (Html.BeginForm("FinalizarReserva", "Peliculas", FormMethod.Post))
        {
            @Html.Hidden("Pelicula", pelicula.IdPelicula)

            @Html.Label("Version", new { @class = "margin-dp" })
            @Html.DropDownList("Version", ViewData["version"] as List<SelectListItem>, "Por Favor, seleccione una Version", new { @class = "margin-dp form-control"  })

            @Html.Label("Sede", new { @class = "margin-dp" })
            @Html.DropDownList("Sede", new SelectList(string.Empty, "Value", "Text"), "Por Favor, seleccione una sede", new { @class = "margin-dp form-control" })

            @Html.Label("Dia", new { @class = "margin-dp" })
            @Html.DropDownList("Dia", new SelectList(string.Empty, "Value", "Text"), "Por favor, Seleccione un dia", new { @class = "margin-dp form-control" })

            @Html.Label("Horario", new { @class = "margin-dp" })
            @Html.DropDownList("Horario", new SelectList(string.Empty, "Value", "Text"), "Por favor, Seleccione un horario", new { @class = "margin-dp form-control" })

            <button type="submit" class="margin-dp btn btn-success">Continuar</button>

            if (ViewData["error"] != null)
            {

                <p class="alert-danger margin-dp error">@Html.Display("error", ViewData["error"])</p>
                
            }

        }

    </div>
    


</div>
}